"""Add user_id foreign key to decks

Revision ID: 978f7e12ffc5
Revises: 092ae2dd2911
Create Date: 2024-12-16 21:09:39.975176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978f7e12ffc5'
down_revision = '092ae2dd2911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_decks_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
