"""Add image_url column to words table

Revision ID: 81caab4025ea
Revises: 502c826bfa4e
Create Date: 2024-12-16 19:37:17.046481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81caab4025ea'
down_revision = '502c826bfa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('card_count')

    # ### end Alembic commands ###
