"""Add image_url column to words table

Revision ID: 502c826bfa4e
Revises: 736c450c2e94
Create Date: 2024-12-16 19:25:55.607578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502c826bfa4e'
down_revision = '736c450c2e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipa', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lemma', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('lemma')
        batch_op.drop_column('ipa')

    # ### end Alembic commands ###
