"""Add pronunciation, definition, and example fields to words table

Revision ID: e5077de9ed86
Revises: 978f7e12ffc5
Create Date: 2024-12-19 17:00:54.881709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5077de9ed86'
down_revision = '978f7e12ffc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pronunciation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('definition', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('example_sentence', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('example_translation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_column('example_translation')
        batch_op.drop_column('example_sentence')
        batch_op.drop_column('definition')
        batch_op.drop_column('pronunciation')

    # ### end Alembic commands ###
